server:
  port: 8080

spring:
  application:
    name: background-task-executor

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: info
